{
 "title": "http requests",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "http code 200",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "prometheus_http_requests_total{code=\"200\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http code 400",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "prometheus_http_requests_total{code=\"400\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http code compare",
   "type": "piechart",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_http_requests_total{code=\"200\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(prometheus_http_requests_total{code=\"400\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}