version: '3.3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana-wrong:
    # image: public.ecr.aws/f5g2i5c5/grafana-qday
    build: ./grafana-wrong
    ports:
      - '3000:3000'

  grafana-clean:
    image: grafana/grafana
    ports:
      - '3001:3000'
  
  # promtail:
  #   image: grafana/promtail:2.9.4

  # loki:
  #   image: grafana/loki:2.9.4
  #   ports:
  #     - '3100:3100'
      
